# Generated by Django 5.0.1 on 2024-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('E', '---------'), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1),
        ),
    ]
