# Generated by Django 5.0.1 on 2024-01-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='idade',
        ),
    ]
