# Generated by Django 5.0.1 on 2024-01-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_funcionario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
