# Generated by Django 5.0.1 on 2024-02-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
